# Forward modified Enter/etc so Ctrl+Enter and Shift+Enter work in apps like pi
set -g extended-keys on
set -g extended-keys-format csi-u

# split panes using | and -
bind / split-window -h
bind v split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# switch panes using Alt-hjkl without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# don't rename windows automatically
set-option -g allow-rename off

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour yellow

# copy mode
setw -g mode-style 'fg=black bg=red bold'

# panes
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=yellow'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=red'

set -g status-left ''
set -g status-left-length 10

set -g status-right-style 'fg=black bg=yellow'
set -g status-right ''
set -g status-right-length 50

setw -g window-status-current-style 'fg=black bg=red'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=red bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '

setw -g window-status-bell-style 'fg=yellow bg=red bold'

set -g status-position top

# messages
set -g message-style 'fg=yellow bg=red bold'

# 1 base-index
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# New window
unbind w
bind w new-window

# no confirmation when killing pane or window
bind x kill-pane

# switch windows using Alt-1 through Alt-9 without prefix
# create the window if it doesn't exist yet
bind 1 if-shell 'tmux select-window -t :1' '' 'new-window -t :1'
bind 2 if-shell 'tmux select-window -t :2' '' 'new-window -t :2'
bind 3 if-shell 'tmux select-window -t :3' '' 'new-window -t :3'
bind 4 if-shell 'tmux select-window -t :4' '' 'new-window -t :4'
bind 5 if-shell 'tmux select-window -t :5' '' 'new-window -t :5'
bind 6 if-shell 'tmux select-window -t :6' '' 'new-window -t :6'
bind 7 if-shell 'tmux select-window -t :7' '' 'new-window -t :7'
bind 8 if-shell 'tmux select-window -t :8' '' 'new-window -t :8'
bind 9 if-shell 'tmux select-window -t :9' '' 'new-window -t :9'

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Plugins
set -g @plugin 'accessd/tmux-agent-indicator'
